---
title: "CBASS_tempplots"
author: "Cheryl"
date: "3/7/2019"
output: html_document
---

```{r load libraries, include=FALSE}
library(tidyverse)
library(ggplot2)
library(lubridate)
library(reshape2)  # after install.packages('reshape2')
```

Load in data
```{r import data, include=FALSE}
# important!! remove mutliple headers in text wrangler first!!
CBASS1_log <- read_csv("/Users/loga8761/Google Drive/Galapagos/CBASS/CBASS1_LOG_03032019.csv")

CBASS1_log2 <- read_csv("/Users/loga8761/Google Drive/Galapagos/CBASS/CBASS1_LOG_03062019.TXT")

CBASS2_log <- read_csv("/Users/loga8761/Google Drive/Galapagos/CBASS/CBASS2_LOG_03032019.TXT")
  
CBASS2_log2 <- read_csv("/Users/loga8761/Google Drive/Galapagos/CBASS/CBASS2_LOG_03062019.TXT")

```

Select relevant data for CBASS 1

```{r select CBASS1 data, include=FALSE}
CBASS1_log <- CBASS1_log %>%
  separate(Date,c("y","m","d"))
#make time stamp
CBASS1_log$datetime<-ymd_hms(paste(CBASS1_log$y, CBASS1_log$m, CBASS1_log$d,CBASS1_log$Th, CBASS1_log$Tm,CBASS1_log$Ts, sep="-"))
str(CBASS1_log)
#select & gather data
CBASS1_log <- CBASS1_log %>%
  select(datetime,T1inT,T2inT,T3inT,T4inT) %>%
  gather("tank", temperature, 2:5)

CBASS1_log2 <- CBASS1_log2 %>%
  separate(Date,c("y","m","d"))
#make time stamp
CBASS1_log2$datetime<-ymd_hms(paste(CBASS1_log2$y, CBASS1_log2$m, CBASS1_log2$d,CBASS1_log2$Th, CBASS1_log2$Tm,CBASS1_log2$Ts, sep="-"))
str(CBASS1_log2)

CBASS1_log2 <- CBASS1_log2 %>%
  select(datetime,T1inT,T2inT,T3inT,T4inT) %>%
  gather("tank", temperature, 2:5)
```

Make datestamp for CBASS2
```{r select CBASS1 data, include=FALSE}
CBASS2_log <- CBASS2_log %>%
separate(Date,c("y","m","d"))
# make timestamp
CBASS2_log$datetime<-ymd_hms(paste(CBASS2_log$y, CBASS2_log$m, CBASS2_log$d,CBASS2_log$Th, CBASS2_log$Tm,CBASS2_log$Ts, sep="-"))
str(CBASS2_log)
# select & gather data
CBASS2_log <- CBASS2_log %>%
  select(datetime,T1inT,T2inT,T3inT,T4inT) %>%
  gather("tank", temperature, 2:5)

CBASS2_log2 <- CBASS2_log2 %>%
separate(Date,c("y","m","d"))
# make timestamp
CBASS2_log2$datetime<-ymd_hms(paste(CBASS2_log2$y, CBASS2_log2$m, CBASS2_log2$d,CBASS2_log2$Th, CBASS2_log2$Tm,CBASS2_log2$Ts, sep="-"))
str(CBASS2_log2)
# select & gather data
CBASS2_log2 <- CBASS2_log2 %>%
  select(datetime,T1inT,T2inT,T3inT,T4inT) %>%
  gather("tank", temperature, 2:5)

```


Plot data CBASS1 Heat Ramp
```{r Plot CBASS1 Heat Ramp, include=FALSE}
ggplot(CBASS1_log,aes(x=datetime, y=temperature)) +
  geom_point(size=.3) +
  aes(color = tank) +
  #facet_grid(. ~ tank) +
  theme_bw() + ylim(25, 35) +
  scale_x_datetime(limits = ymd_hms(c("2019-Mar-2-13-00-00","2019-Mar-3-10-00-00"))) +
  ggtitle("CBASS1_Heat_Ramp")
  ggsave("CBASS1_Heat_Ramp_Mar2.png", width = 6, height = 3)
```

Plot data CBASS1 Cold Ramp
```{r Plot CBASS1 Cold Ramp, include=FALSE}
ggplot(CBASS1_log2,aes(x=datetime, y=temperature)) +
  geom_point(size=.3) +
  aes(color = tank) +
  #facet_grid(. ~ tank) +
  theme_bw() + ylim(10, 30) +
  scale_x_datetime(limits = ymd_hms(c("2019-Mar-4-13-00-00","2019-Mar-5-10-00-00"))) +
  ggtitle("CBASS1_Cold_Ramp")
  ggsave("CBASS1_Cold_Ramp_Mar4.png", width = 6, height = 3)
```

Plot data CBASS2 Heat Ramp
```{r Plot CBASS2 Heat Ramp, include=FALSE}
ggplot(CBASS2_log,aes(x=datetime, y=temperature)) +
  geom_point(size=.3) +
  aes(color = tank) +
  #facet_grid(. ~ species) +
  theme_bw() + ylim(25, 35) +
  ggtitle("CBASS2_Heat_Ramp") +
  scale_x_datetime(limits = ymd_hms(c("2019-Mar-2-13-00-00","2019-Mar-3-10-00-00")))
  ggsave("CBASS2_Heat_Ramp_Mar2.png", width = 6, height = 3)
```

Plot data CBASS2 Cold Ramp
```{r Plot CBASS2 Cold Ramp, include=FALSE}
ggplot(CBASS2_log2,aes(x=datetime, y=temperature)) +
  geom_point(size=.3) +
  aes(color = tank) +
  #facet_grid(. ~ species) +
  theme_bw() + ylim(10, 30) +
  ggtitle("CBASS2_Cold_Ramp") +
  scale_x_datetime(limits = ymd_hms(c("2019-Mar-4-13-00-00","2019-Mar-5-10-00-00"))) +
  ggsave("CBASS2_Cold_Ramp_Mar4.png", width = 6, height = 3)
```
