---
title: "ColonyTolerance"
author: "Cheryl Logan"
date: "6/9/2021"
output: html_document
params:
  Species: Pocillopora_sp
  RampType: Heat
  printcode: TRUE
  data: /Users/loga8761/github/PAM/Galapagos_all.csv

---

# Load libraries
```{r setup, include = FALSE}
library(tidyverse)
library(ggplot2)
library(ggpubr)
library(broom)
```

# Load data 
```{r load.data, include = FALSE}
# from "Galapagos_PAM_allsites.Rmd"
# Remove sites with odd data or different temp profiles
PAM_all <- read_csv("/Users/loga8761/github/PAM/Galapagos_all.csv") %>%
  filter(Site != "AcademyBay"& Site != "Floreana") %>%
  mutate(Site = fct_relevel(Site, 
            "Darwin", "Wolf2", "Punta_Pitt", 
            "Espanola", "Isabela"))  

pam.data <- PAM_all %>%
  filter(Species == params$Species) %>%
  filter(RampType == params$RampType) 
  
#Labels for re-ordering site names (warm -> cold)
SiteLabels <- c("Darwin", "Wolf","San Cristobal", "Espanola", "Isabela")
```

# Identify most/least tolerant colonies
```{r top.corals}
#Fit linear model for each genotype across all temperatures
pam.data <- pam.data %>% drop_na(PAMChange) # remove NAs
slopes<-pam.data %>% group_by(Genobysite) %>% do(tidy(lm(PAMChange ~ Treatment, .)))

slopes <-slopes %>%
  ungroup() %>%
  filter(term=="Treatment")  %>%  # filter by slopes only
  mutate(estimate = abs(estimate)) %>%  # abs value so code works for heat/cold 
  mutate(tolerance = ntile(estimate,4)) %>%  # bin slopes low->high (25:50:25)
  mutate(tolerance = ifelse(tolerance == 1, "most_tolerant",ifelse(tolerance == 4,"least_tolerant","moderate") ))

slopes_corals <-right_join(pam.data, slopes, by = "Genobysite")
```

# Plot weakest & stronge genotypes
```{r weak.strong}
ggplot(data=slopes_corals, 
    aes(x=Treatment, y=PAMChange, label= Treatment, group=Genobysite, color=Site)) +
  #scale_fill_manual(values = c ("#56B4E9", "#E69F00"), name = "Reef site") +
  geom_point()+
  geom_smooth(method = "lm", se = FALSE)+
  facet_grid(~tolerance, space = "free", scales = "free")+ #this can also be used but rows and columns have to be specified -> facet_grid(. ~ experiment)
  theme_bw() +
  annotate("segment", x=-Inf, xend=-Inf, y=-Inf, yend=Inf, colour = "black", size=2)+
  scale_fill_discrete(name = "Site", labels = SiteLabels) +
  ggtitle(paste0('GenotypeTolerance_', params$Species, '_', params$RampType)) 
ggsave("Figures/GenoTolerance_Heat_POC_06102021.pdf", width = 10, height = 6)
```

# Plot weakest & stronge genotypes by site

(next: are any genotypes most heat AND cold tolerant?)
```{r hist}
hist <- slopes_corals %>%
  select(Genobysite, Site, tolerance) %>%
  unique() %>%
  select(Site, tolerance) 

ggplot(hist, aes(x=Site,fill = factor(tolerance)))+
  geom_bar(stat="count") +
  scale_x_discrete(labels=SiteLabels) +
  scale_fill_brewer(palette="OrRd") + theme_minimal()+
  ggtitle(paste0('StrongestColoniesbySite_', params$Species, '_', params$RampType)) 
ggsave("Figures/StrongestbySite_Heat_POC_06112021.pdf", width = 10, height = 6)
```