---
title: "DRC_models"
author: "Cheryl Logan"
date: "6/24/2021"
output: html_document
params:
  Species: Pocillopora_sp
  RampType: Heat
  printcode: TRUE
  data: /Users/loga8761/github/PAM/Galapagos_all.csv
---

Help here:
http://www.darrenkoppel.com/2020/09/04/dose-response-modelling-and-model-selection-in-r/

# Load libraries
```{r setup, include = FALSE}
library(tidyverse)
library(ggpubr)
library(broom)
library(drc)
library(modelr)
library(nlstools)
```

# Load data 
```{r load.data, include = FALSE}
# from "Galapagos_PAM_allsites.Rmd"
# Remove sites with odd data or different temp profiles
PAM_all <- read_csv("/Users/loga8761/github/PAM/Galapagos_all.csv") %>%
  filter(Site != "AcademyBay"& Site != "Floreana") %>%
  mutate(Site = fct_relevel(Site, 
            "Darwin", "Wolf2", "Punta_Pitt", 
            "Espanola", "Isabela"))  

pam.data <- PAM_all %>%
  filter(Species == params$Species) %>%
  filter(RampType == params$RampType) 

pam.data <- 
  pam.data %>% 
  mutate_at("Genobysite", str_replace, "Pocillopora_sp", "POC") %>% 
  mutate_at("Genobysite", str_replace, "Wolf2", "Wolf") %>% 
  mutate_at("Genobysite", str_replace, "Punta_Pitt", "San_Cristobal")

#Labels for re-ordering site names (warm -> cold)
SiteLabels <- c("Darwin", "Wolf","San Cristobal", "Espanola", "Isabela")
```

# Run Model on all data

Prepare data
```{r prep.data}
# make genotype a factor
pam.data$Genobysite<-as.factor(pam.data$Genobysite)
pam.data$FacTemp<-as.factor(pam.data$Treatment) #make treatment a factor
pam.data$Treatment <- as.integer(pam.data$Treatment) # not sure if this matters
```

Run model
```{r define.fxn, include = FALSE}}
# define drm function to use with map
drm.func <- function(x) {
  drm(PAM ~ Treatment, data = x, 
      fct = LL.3(names = c("hill", "max", "ED50")),
      upperl = c(120, 0.72, 40),  # from R. Cunning
      lowerl = c(10, 0.55, 30))}  # from R. Cunning

predict.fun <- function(x) {
  add_predictions(data.frame(Treatment = seq(26,40)), x)
}

coefs.fun <- function(x) {coef(x) %>% tidy}

# run three-parameter log-logistic function (LL.3) using drc package on each colony
df2 <- pam.data %>% 
  group_by(Site) %>% # not sure if this does anything
  group_by(Genobysite) %>% 
  nest() %>%
              mutate(drmod = map(data, drm.func), 
                     pred = map(drmod, predict.fun),
                     coefs = map(drmod, coefs.fun)) 

ED(df2 %>% group_by(Genobysite) %>% unnest(drmod), c(10,25,50)) # get ed25 values
```


```{r}
mod1 <- drm(PAM ~ Treatment, data = pam.data, curveid=Genobysite,
      fct = LL.3(names = c("hill", "max", "ED50")))

# Find best model fit via AIC
aic <- mselect(mod1, list(LL.3(),LL.4(), W1.3()), linreg = TRUE)

## Fine-tuning the axis break
plot(mod1, broken = TRUE, bcontrol = list(style = "gap"))


# try this plot package
tidydrc_plot(mod1,ed50 = TRUE, confint = TRUE, color = ~Site)
  
  
## Plot with confidence regions
  ggplot(mod1) +
     geom_point(aes(Treatment, PAM, color=Site, group=Site)) +
     geom_line(aes(Treatment, pred), data =
                                      mod1 %>% unnest(pred)) +
     geom_vline(aes(xintercept = x), 
                  linetype = 5,
                  data = mod1 %>% unnest(coefs) %>% filter(names == "ED50:(Intercept)")) +
     #geom_text(aes(df2 %>% unnest(coefs) %>% filter(names == "ED50:(Intercept)")), size=3) +
     facet_wrap(Genobysite) +
     theme_bw() + 
     theme(legend.position = "none")
  

## Calculating EC/ED values
ED(mod1, c(10, 25, 50))

anova(mod1)aic



tidy(mod, conf.int = TRUE)
glance(mod)
```

Plot data
```{r plot}
# plot raw data, model and ED50 line

# Sites <-pam.data %>% # get site names
#    dplyr::select(Site,Genobysite) %>% unique()
# 
# df2 <- inner_join(df2,Sites, by = "Genobysite") %>%# add Site to df2 
#   mutate(Location= Site)

df2 %>%  group_by(Genobysite) %>% unnest(data) %>% 
  ggplot() + 
     geom_point(aes(Treatment, PAM, color=Site, group=Site)) +
     geom_line(aes(Treatment, pred), data =
                                      df2 %>% unnest(pred)) +
     geom_vline(aes(xintercept = x), 
                  linetype = 5,
                  data = df2 %>% unnest(coefs) %>% filter(names == "ED50:(Intercept)")) +
     #geom_text(aes(df2 %>% unnest(coefs) %>% filter(names == "ED50:(Intercept)")), size=3) +
     facet_wrap(Genobysite) +
     theme_bw() + 
     theme(legend.position = "none")

#ggsave("LL3.plots_POC.png", width = 10, height = 6)

# summary of coefficients
df2 %>% unnest(coefs) %>% spread(names, x) 
```

Get ed50 values
```{r plot}
# get ED50 values for each genotype!
ED50 <- df2 %>%
  dplyr::select(Genobysite, coefs) %>%
  unnest(coefs) %>%
  filter(names == "ED50:(Intercept)") %>% 
  arrange(x) %>%  # sort
  rename(ed50 = x)

# Collect raw data, fitted values, and ed50 estimates
df3 <- full_join(pam.data, ED50, by = "Genobysite")
```

# plot heat tolerant genotypes by site
```{r hist}
hist <-df3 %>%
  dplyr::select(Genobysite, Site, ed50) %>%
  unique()

# categorize by tolerance level (low, mod,high)
hist <- hist  %>%
  mutate(tolerance = ntile(ed50,4)) %>%  # bin slopes low->high (25:50:25)
  mutate(tolerance2 = ifelse(tolerance == 4, "most_tolerant",ifelse(tolerance == 1,"least_tolerant","moderate") ))

#ggplot(hist, aes(x=Site,fill = factor(tolerance2)))+
ggplot(hist, aes(x=Site,factor(tolerance2))+
  geom_bar(stat="count") +
  scale_x_discrete(labels=SiteLabels) +
  scale_fill_brewer(palette="Reds") + theme_minimal()+  # Blues for cold tolerance barplots
  ggtitle(paste0('StrongestColoniesbySite_', params$Species, '_', params$RampType)) 
#ggsave("Figures/LL.3_StrongestbySite_Heat_PAV_06242021.pdf", width = 10, height = 6)
```

# Run Model for each colony (from Dan)

```{r}
# run LL.3 on genotypes
DRCpamgeno = drm(PAM~Treatment, data = pam.data, curveid = Genobysite,
             fct = LL.3(names = c('hill', 'max', 'ed50')))
summary(DRCpamgeno)
compParm(DRCpamgeno, 'ed50')
compParm(DRCpamgeno, 'ed50', "-")
plot(DRCpamgeno)
ED(DRCpamgeno, c(50))[,1]
```

# Plot data (from Dan)

```{r}

pdf("../plots/2021-06-08_CarlysInshorePastRNASeq_DRC_genofits.pdf",10,7)
par(mar=c(5.1,5.1,4.1,2.1))
Line_width=2.5
with(pam.data, plot(Treatment,PAM,xlim=c(29.5,41),ylim=c(0,0.60), type='n', cex.axis=2.5, cex.lab=2.5, ylab="Fv/Fm", xlab="Temperature °C"))
Colours<-c('#4575b4','#74add1','#fee090','#f46d43','#d73027')

for(i in order(DRCpamgeno$coefficients[11:15])){
  Geno=names(table(pam.data$Genobysite))[i]
  print(Geno)
  print(summary(mod1<-drm(PAM ~ Treatment, data=pam.data[pam.data$Genobysite==Genobysite,],fct = LL.3(names = c('hill', 'max', 'ed50')))))
  points(pam.data[pam.data$Genobysite==Genobysite,"Temp"],pam.data[pam.data$Genobysite==Genobysite,"PAM"], col=Colours[i], pch=16)
  lines(temp_x, predict(mod1, data.frame(Temp = temp_x)), col=Colours[i], lwd=Line_width)
}

abline(v=DRCpamgeno$coefficients[11:15][order(DRCpamgeno$coefficients[11:15])], col=Colours, lwd=Line_width)
legend("bottomleft", col=Colours, lty=1, cex=1.75, lwd=Line_width, paste0(names(DRCpamgeno$coefficients)[11:15][order(DRCpamgeno$coefficients[11:15])],": ",round(DRCpamgeno$coefficients[11:15][order(DRCpamgeno$coefficients[11:15])], digits=2)))
dev.off()

```

