---
title: "Coral_rTPC"
author: "Cheryl"
date: "6/18/2019"
output: html_document
---

```{r setup, include=FALSE}
# install.packages('remotes')
#remotes::install_github('padpadpadpad/rTPC') # install package
library(rTPC)
library(nls.multstart) # devtools::install_github('padpadpadpad/nls.multstart')
library(ggplot2)
library(broom)
library(purrr)
library(dplyr)
library(tidyr)
library(nlstools)
library(tidyverse)
library(kableExtra)
library(MuMIn)

# write function to label ggplot2 panels
label_facets_num <- function(string){
  len <- length(string)
  string = paste('(', 1:len, ') ', string, sep = '')
  return(string)
}

# write function to convert label text size to points
pts <- function(x){
  as.numeric(grid::convertX(grid::unit(x, 'points'), 'mm'))
}
```

Look at sample data
```{r cars}
data("chlorella_tpc")
d <- read_csv("/Users/loga8761/github/PAM/PAM_all_TPCtest.csv")
#d <- chlorella_tpc

# show the data
ggplot(d, aes(temp, PAM, group = curve_id)) +
  facet_grid(Species ~ Site) +
  geom_point(alpha = 0.5) +
  geom_line(alpha = 0.5) +
  theme_bw()
```
```{r}
# filter data for just a single curve
d_1 <- filter(d, curve_id == 70, Replicate == "A")

# run in purrr - going to be a huge long command this one
d_models <- group_by(d_1, curve_id, Replicate) %>%
  nest() %>%
  mutate(., lactin2 = map(data, ~nls_multstart(PAM ~ lactin2_1995(temp = temp, a, b, tmax, delta_t),
                       data = .x,
                       iter = 500,
                       start_lower = get_start_vals(.x$temp, .x$PAM, model_name = 'lactin2_1995') - 2,
                       start_upper = get_start_vals(.x$temp, .x$PAM, model_name = 'lactin2_1995') + 2,
                       supp_errors = 'Y')),
            sharpeschoolhigh = map(data, ~nls_multstart(PAM ~ sharpeschoolhigh_1981(temp = temp, r_tref, e, eh, th, tref = 15),
                                           data = .x,
                                           iter = 500,
                                           start_lower = get_start_vals(.x$temp, .x$PAM, model_name = 'sharpeschoolhigh_1981') - 10,
                                           start_upper = get_start_vals(.x$temp, .x$PAM, model_name = 'sharpeschoolhigh_1981') + 10,
                                           supp_errors = 'Y')),
            johnsonlewin = map(data, ~nls_multstart(PAM ~ johnsonlewin_1946(temp = temp, r0, e, eh, topt),
                                           data = .x,
                                           iter = 500,
                                           start_lower = c(r0 = 1e9, e = 0, eh = 0, topt = 270),
                                           start_upper = c(r0 = 1e11, e = 2, eh = 10, topt = 330),
                                           supp_errors = 'Y')),
            thomas = map(data, ~nls_multstart(PAM ~ thomas_2012(temp = temp, a, b, c, topt),
                                           data = .x,
                                           iter = 500,
                                           start_lower = get_start_vals(.x$temp, .x$PAM, model_name = 'thomas_2012') - 1,
                                           start_upper = get_start_vals(.x$temp, .x$PAM, model_name = 'thomas_2012') + 2,
                                           supp_errors = 'Y',
                                           lower = get_lower_lims(.x$temp, .x$PAM, model_name = 'thomas_2012'))),
            briere2 = map(data, ~nls_multstart(PAM ~ briere2_1999(temp = temp, tmin, tmax, a, b),
                                           data = .x,
                                           iter = 500,
                                           start_lower = get_start_vals(.x$temp, .x$PAM, model_name = 'briere2_1999') - 1,
                                           start_upper = get_start_vals(.x$temp, .x$PAM, model_name = 'briere2_1999') + 1,
                                           supp_errors = 'Y',
                                           lower = get_lower_lims(.x$temp, .x$PAM, model_name = 'briere2_1999'),
                                           upper = get_upper_lims(.x$temp, .x$PAM, model_name = 'briere2_1999'))),
            spain = map(data, ~nls_multstart(PAM ~ spain_1982(temp = temp, a, b, c, r0),
                                           data = .x,
                                           iter = 500,
                                           start_lower = c(a = -1, b = -1, c = -1, r0 = -1),
                                           start_upper = c(a = 1, b = 1, c = 1, r0 = 1),
                                           supp_errors = 'Y')),
            ratkowsky = map(data, ~nls_multstart(PAM ~ ratkowsky_1983(temp = temp, tmin, tmax, a, b),
                                           data = .x,
                                           iter = 500,
                                           start_lower = get_start_vals(.x$temp, .x$PAM, model_name = 'ratkowsky_1983') - 2,
                                           start_upper = get_start_vals(.x$temp, .x$PAM, model_name = 'ratkowsky_1983') + 2,
                                           supp_errors = 'Y')),
            boatman = map(data, ~nls_multstart(PAM ~ boatman_2017(temp = temp, rmax, tmin, tmax, a, b),
                                           data = .x,
                                           iter = 500,
                                           start_lower = get_start_vals(.x$temp, .x$PAM, model_name = 'boatman_2017') -1,
                                           start_upper = get_start_vals(.x$temp, .x$PAM, model_name = 'boatman_2017') + 1,
                                           supp_errors = 'Y')),
            flinn = map(data, ~nls_multstart(PAM ~ flinn_1991(temp = temp, a, b, c),
                                           data = .x,
                                           iter = 500,
                                           start_lower = get_start_vals(.x$temp, .x$PAM, model_name = 'flinn_1991') - 10,
                                           start_upper = get_start_vals(.x$temp, .x$PAM, model_name = 'flinn_1991') + 10,
                                           supp_errors = 'Y')),
            gaussian = map(data, ~nls_multstart(PAM ~ gaussian_1987(temp = temp, rmax, topt, a),
                                           data = .x,
                                           iter = 500,
                                           start_lower = get_start_vals(.x$temp, .x$PAM, model_name = 'gaussian_1987') - 2,
                                           start_upper = get_start_vals(.x$temp, .x$PAM, model_name = 'gaussian_1987') + 2,
                                           supp_errors = 'Y')),
            oneill = map(data, ~nls_multstart(PAM ~ oneill_1972(temp = temp, rmax, tmax, topt, q10),
                                           data = .x,
                                           iter = 500,
                                           start_lower = get_start_vals(.x$temp, .x$PAM, model_name = 'oneill_1972') - 1,
                                           start_upper = get_start_vals(.x$temp, .x$PAM, model_name = 'oneill_1972') + 1,
                                           supp_errors = 'Y')),
            joehnk = map(data, ~nls_multstart(PAM ~ joehnk_2008(temp = temp, rmax, topt, a, b, c),
                                           data = .x,
                                           iter = 500,
                                           start_lower = get_start_vals(.x$temp, .x$PAM, model_name = 'joehnk_2008') - 1,
                                           start_upper = get_start_vals(.x$temp, .x$PAM, model_name = 'joehnk_2008') + 1,
                                           supp_errors = 'Y',
                                           lower = get_lower_lims(.x$temp, .x$PAM, model_name = 'joehnk_2008'))),
            kamykowski = map(data, ~nls_multstart(PAM ~ kamykowski_1985(temp = temp, tmin, tmax, a, b, c),
                                           data = .x,
                                           iter = 500,
                                           start_lower = c(tmin = 0, tmax = 10, a = -3, b = -1, c = -1),
                                           start_upper = c(tmin = 20, tmax = 50, a = 3, b = 1, c =1),
                                           supp_errors = 'Y')),
            quadratic = map(data, ~nls_multstart(PAM ~ quadratic_2008(temp = temp, a, b, c),
                                           data = .x,
                                           iter = 500,
                                           start_lower = c(a = 0, b = -2, c = -1),
                                           start_upper = c(a = 30, b = 2, c = 1),
                                           supp_errors = 'Y')),
            hinshelwood = map(data, ~nls_multstart(PAM ~ hinshelwood_1947(temp = temp, a, e, c, eh),
                                           data = .x,
                                           iter = 500,
                                           start_lower = c(a = 1e9, e = 5, c = 1e9, eh = 0),
                                           start_upper = c(a = 1e11, e = 20, c = 1e11, eh = 20),
                                           supp_errors = 'Y')),
            sharpeschoolfull = map(data, ~nls_multstart(PAM ~ sharpeschoolfull_1981(temp = temp, r_tref, e, el, tl, eh, th, tref = 15),
                                           data = .x,
                                           iter = 500,
                                           start_lower = get_start_vals(.x$temp, .x$PAM, model_name = 'sharpeschoolfull_1981') - 10,
                                           start_upper = get_start_vals(.x$temp, .x$PAM, model_name = 'sharpeschoolfull_1981') + 10,
                                           supp_errors = 'Y')),
            sharpeschoollow = map(data, ~nls_multstart(PAM ~ sharpeschoollow_1981(temp = temp, r_tref, e, el, tl, tref = 15),
                                           data = .x,
                                           iter = 500,
                                           start_lower = c(r_tref = 0.01, e = 0, el = 0, tl = 270),
                                           start_upper = c(r_tref = 2, e = 3, el = 10, tl = 330),
                                           supp_errors = 'Y')),
            weibull = map(data, ~nls_multstart(PAM ~ weibull_1995(temp = temp, a, topt, b, c),
                                           data = .x,
                                           iter = 500,
                                           start_lower = c(a = 0, topt = 30, b = 100, c = 10),
                                           start_upper = c(a = 3, topt = 50, b = 200, c = 50),
                                           lower = c(a = 0, topt = 20, b = 0, c = 0),
                                           supp_errors = 'Y')))
            # rezende = map(data, ~nls_multstart(PAM ~ rezende_2019(temp = temp, a, q10, b, c),
            #                                data = .x,
            #                                iter = 500,
            #                                start_lower = get_start_vals(.x$temp, .x$PAM, model_name = 'rezende_2019') * 0.8,
            #                                start_upper = get_start_vals(.x$temp, .x$PAM, model_name = 'rezende_2019') * 1.2,
            #                                upper = get_upper_lims(.x$temp, .x$PAM, model_name = 'rezende_2019'),
            #                                lower = get_lower_lims(.x$temp, .x$PAM, model_name = 'rezende_2019'),
            #                                supp_errors = 'Y')))
```

Extract parameters and visualise our model fits.
```{r}
# stack models
d_stack <- gather(d_models, 'model', 'output', 6:ncol(d_models))

# preds
newdata <- tibble(temp = seq(min(d_1$temp), max(d_1$temp), length.out = 100))
d_preds <- d_stack %>%
  mutate(., preds = map(output, augment, newdata = newdata)) %>%
  unnest(preds)

# estimate parameters
params <- d_stack %>%
  mutate(., est = map(output, tidy)) %>%
  select(., -c(data, output)) %>%
  unnest(est)

# plot fit
ggplot(d_preds, aes(temp, PAM)) +
  geom_point(aes(temp, PAM), d_1) +
  geom_line(aes(temp, .fitted, col = model)) +
  facet_wrap(~model, labeller = labeller(model = label_facets_num)) +
  theme_bw(base_size = 16) +
  theme(legend.position = 'none',
        strip.text = element_text(hjust = 0),
        strip.background = element_blank()) +
  xlab('Temperature (ºC)') +
  ylab('rate') +
  geom_hline(aes(yintercept = 0), linetype = 2)
```
```{r}
# estimate extra parameters
params_extra <- d_stack %>%
  mutate(., est = map(output, est_params)) %>%
  select(., -c(data, output)) %>%
  unnest(est) %>%
  ungroup() %>%
  select(c(model, rmax:ncol(.))) %>%
  mutate_if(is.numeric, function(x) round(x, 2))

# set column names for html table
col_names <- c('model', 'Rmax', 'Topt', 'CTmin', 'CTmax', 'E', 'Eh', 'Q10', 'thermal\nsafety\nmargin', 'tolerance\nrange', 'skewness')

# show the table of extra parameters
head(params_extra) %>%
  kableExtra::kable(., col.names = col_names, align = 'c') %>%
  kableExtra::kable_styling(font_size = 14, bootstrap_options = c("striped", "hover", "condensed"), position = 'center')
```
Fitting multiple models to multiple curves

```{r}
# filter 15 curves
d_10 <- filter(d, curve_id <= 10)

# when scaling up our code to fit hundreds of models, its nice to have a progress bar
nls_multstart_progress <- function(formula, data = parent.frame(), iter, start_lower, 
                                   start_upper, supp_errors = c("Y", "N"), convergence_count = 100, 
                                   control, modelweights, ...){
  if(!is.null(pb)){
    pb$tick()$print()
  }
  nls_multstart(formula = formula, data = data, iter = iter, start_lower = start_lower, 
                start_upper = start_upper, supp_errors = supp_errors, convergence_count = convergence_count, 
                control = control, modelweights = modelweights, ...)
}


# start progress bar and estimate time it will take
number_of_models <- 5
number_of_curves <- length(unique(d_10$curve_id))

# setup progress bar
pb <- progress_estimated(number_of_curves*number_of_models)

# run each model on each curve
d_models <- group_by(d_10, curve_id, Site, Replicate, Species) %>%
  nest() %>%
  mutate(., lactin2 = map(data, ~nls_multstart_progress(PAM ~ lactin2_1995(temp = temp, p, c, tmax, delta_t),
                       data = .x,
                       iter = 500,
                       start_lower = c(p = 0, c = -2, tmax = 35, delta_t = 0),
                       start_upper = c(p = 3, c = 0, tmax = 55, delta_t = 15),
                       supp_errors = 'Y')),
            sharpeschoolhigh = map(data, ~nls_multstart_progress(PAM ~ sharpeschoolhigh_1981(temp = temp, r_tref, e, eh, th, tref = 15),
                       data = .x,
                       iter = 500,
                       start_lower = get_start_vals(.x$temp, .x$PAM, model_name = 'sharpeschoolhigh_1981') - 5,
                       start_upper = get_start_vals(.x$temp, .x$PAM, model_name = 'sharpeschoolhigh_1981') + 5,
                       supp_errors = 'Y')),
            gaussian = map(data, ~nls_multstart_progress(PAM ~ gaussian_1987(temp = temp, rmax, topt, a),
                        data = .x,
                        iter = 500,
                        start_lower = c(rmax = 0, topt = 20, a = 0),
                        start_upper = c(rmax = 2, topt = 40, a = 30),
                        supp_errors = 'Y')),
            quadratic = map(data, ~nls_multstart_progress(PAM ~ quadratic_2008(temp = temp, a, b, c),
                        data = .x,
                        iter = 500,
                        start_lower = c(a = 0, b = -2, c = -1),
                        start_upper = c(a = 30, b = 2, c = 1),
                        supp_errors = 'Y')),
            sharpeschoolfull = map(data, ~nls_multstart_progress(PAM ~ sharpeschoolfull_1981(temp = temp, r_tref, e, el, tl, eh, th, tref = 15),
                        data = .x,
                        iter = 500,
                        start_lower = get_start_vals(.x$temp, .x$PAM, model_name = 'sharpeschoolfull_1981') - 5,
                        start_upper = get_start_vals(.x$temp, .x$PAM, model_name = 'sharpeschoolfull_1981') + 5,
                        supp_errors = 'Y')))
```

```{r}
# stack models
d_stack <- gather(d_models, 'model', 'output', 6:ncol(d_models))

# preds
new_data <- tibble(temp = seq(min(d_1$temp), max(d_1$temp), length.out = 100))

# get preds
d_preds <- d_stack %>%
  mutate(., preds = map(output, augment, newdata = newdata)) %>%
  unnest(preds)

# plot preds
lines <- data.frame(val = 0, curve_id = 1:10)

ggplot() +
  geom_point(aes(temp, PAM), d_10) +
  geom_line(aes(temp, .fitted, group = model), alpha = 0.4, d_preds) +
  facet_wrap(~ curve_id, ncol = 5, labeller = labeller(curve_id = label_facets_num)) +
  theme_bw(base_size = 16) +
  theme(legend.position = 'none',
        strip.text = element_text(hjust = 0),
        strip.background = element_blank()) +
  xlab('Temperature (ºC)') +
  ylab('PAM') +
  geom_hline(aes(yintercept = val), linetype = 2, lines) +
  ylim(c(-0.5, 2.5))
```
Extract  parameters for each model for each curve. We can then plot these across each model for each TPC.
```{r}
# estimate extra parameters
params_extra <- d_stack %>%
  mutate(., est = map(output, est_params)) %>%
  select(., -c(data, output)) %>%
  unnest(est)

params_extra <- gather(params_extra, 'term', 'estimate', rmax:ncol(params_extra))

# create jitter position with seeding
pos <- position_dodge(0.4)

ggplot(params_extra, aes(model, estimate, group = curve_id)) +
  geom_line(position = pos, alpha = 0.5) +
  geom_point(position = pos, shape = 21, fill = 'white') +
  facet_wrap(~ term, scales = 'free_y', ncol = 5, labeller = labeller(term = label_facets_num)) +
  theme_bw() +
  theme(legend.position = 'none',
        strip.text = element_text(hjust = 0),
        strip.background = element_blank(),
        axis.text.x = element_text(angle = 30, hjust = 1))
```

Model selection

```{r}
d_stack %>%
  mutate(., info = map(output, glance)) %>%
  select(., curve_id, model, info) %>%
  unnest(info) %>%
  arrange(curve_id) %>%
  select(curve_id, model, sigma, isConv, logLik, AIC, BIC, deviance, df.residual) %>%
  head(5) %>%
  kableExtra::kable(align = 'c', digits = 2) %>%
  kableExtra::kable_styling(font_size = 14, bootstrap_options = c("striped", "hover", "condensed"), position = 'center')
#> Adding missing grouping variables: `growth_temp`, `process`, `flux`
#> Adding missing grouping variables: `growth_temp`, `process`, `flux`
```
Find lowest AIC score
```{r}
# calculate AICc score and filter for the best model for each curve_id
table <- mutate(d_stack, aic = map_dbl(output, possibly(MuMIn::AICc, NA))) %>%
  filter(., !is.na(aic)) %>%
  group_by(curve_id) %>%
  top_n(1, desc(aic)) %>%
  group_by(model) %>%
  tally() %>%
  full_join(., tibble(model = unique(d_stack$model))) %>%
  mutate(., n = replace_na(n, 0)) %>%
  kableExtra::kable(align = 'c', digits = 2) %>%
  kableExtra::kable_styling(font_size = 14, bootstrap_options = c("striped", "hover", "condensed"), position = 'center')
#> Joining, by = "model"

table
```

Model averaging

```{r}
# calculate AICc score and weight models
d_stack <- mutate(d_stack, aic = map_dbl(output, possibly(MuMIn::AICc, NA))) %>%
  filter(., !is.na(aic)) %>%
  group_by(curve_id) %>%
  # filter(., aic - min(aic) <= 2) %>%
  mutate(., weight = MuMIn::Weights(aic)) %>%
  ungroup()

# calculate average prediction
ave_preds <- merge(d_preds, select(d_stack, model, weight, curve_id), by = c('model', 'curve_id')) %>%
  mutate(., temp = round(temp, 2)) %>%
  group_by(temp, curve_id) %>%
  summarise(., ave_pred = sum(.fitted*weight)) %>%
  ungroup()

# plot these
lines <- data.frame(val = 0, curve_id = 1:10)
ggplot() +
  geom_point(aes(temp, PAM), d_10) +
  geom_line(aes(temp, .fitted, group = model), alpha = 0.1, d_preds) +
  geom_line(aes(temp, ave_pred), ave_preds, size = 1) +
  theme_bw(base_size = 16) +
  theme(legend.position = 'none',
        strip.text = element_text(hjust = 0),
        strip.background = element_blank()) +
  facet_wrap(~ curve_id, ncol = 5, labeller = labeller(curve_id = label_facets_num)) +
  xlab('Temperature (ºC)') +
  ylab('rate') +
  ylim(c(-0.5, 2.5)) +
  geom_hline(aes(yintercept = val), linetype = 2, lines)
```

Incorporating model weights
```{r}
d_ave <- filter(d, process == 'adaptation', growth_temp == 20, flux == 'photosynthesis') %>%
  group_by(temp) %>%
  summarise(., sd = sd(PAM),
            ave_rate = mean(PAM)) %>%
  ungroup()

# run both models
d_models <- nest(d_ave) %>%
  mutate(., mod = map(data, ~nls_multstart(ave_rate ~ sharpeschoolhigh_1981(temp = temp, r_tref, e, eh, th, tref = 15),
                                           data = .x,
                                           iter = 500,
                                           start_lower = get_start_vals(.x$temp, .x$ave_rate, model_name = 'sharpeschoolhigh_1981') - 10,
                                           start_upper = get_start_vals(.x$temp, .x$ave_rate, model_name = 'sharpeschoolhigh_1981') + 10,
                                           lower = get_lower_lims(.x$temp, .x$ave_rate, model_name = 'sharpeschoolhigh_1981'),
                                           upper = get_upper_lims(.x$temp, .x$ave_rate, model_name = 'sharpeschoolhigh_1981'),
                                           supp_errors = 'Y')),
         mod_weights = map(data, ~nls_multstart(ave_rate ~ sharpeschoolhigh_1981(temp = temp, r_tref, e, eh, th, tref = 15),
                                           data = .x,
                                           iter = 500,
                                           start_lower = get_start_vals(.x$temp, .x$ave_rate, model_name = 'sharpeschoolhigh_1981') - 10,
                                           start_upper = get_start_vals(.x$temp, .x$ave_rate, model_name = 'sharpeschoolhigh_1981') + 10,
                                           lower = get_lower_lims(.x$temp, .x$ave_rate, model_name = 'sharpeschoolhigh_1981'),
                                           upper = get_upper_lims(.x$temp, .x$ave_rate, model_name = 'sharpeschoolhigh_1981'),
                                           supp_errors = 'Y',
                                           # include weights here!
                                           modelweights = 1/sd)))
#> Warning: `...` must not be empty for ungrouped data frames.
#> Did you want `data = everything()`?

# calculate predictions
d_stack <- gather(d_models, 'model', 'output', starts_with('mod'))

# preds
newdata <- tibble(temp = seq(min(d_ave$temp), max(d_ave$temp), length.out = 100))
d_preds <- d_stack %>%
  mutate(., preds = map(output, augment, newdata = newdata)) %>%
  unnest(preds)

# plot
ggplot() +  
  geom_line(aes(temp, .fitted, group = model, col = model), d_preds) +
  geom_linerange(aes(x = temp, ymin = ave_rate - sd, ymax = ave_rate + sd), d_ave) +
  geom_point(aes(temp, ave_rate), d_ave, size = 3, shape = 21, fill = 'white') +
  theme_bw(base_size = 16) +
  theme(legend.position = 'none',
        strip.text = element_text(hjust = 0),
        strip.background = element_blank()) +
  xlab('Temperature (ºC)') +
  ylab('rate') +
  geom_hline(aes(yintercept = 0), linetype = 2) +
  scale_color_manual(values = c('black', 'red'))
```






