---
title: "A report for `r params$Species` `r params$RampType`"
author: "Cheryl Logan"
date: "6/9/2021"
output: html_document
params:
  Species: Pocillopora_sp
  RampType: Heat
  printcode: TRUE
  data: /Users/loga8761/github/PAM/Galapagos_all.csv

---

# Load libraries
```{r setup, include = FALSE}
library(tidyverse)
library(ggplot2)
library(car)
library(lmerTest)
library(emmeans)
library(ggplot2)
library(ggpubr)
library(sjPlot)
library(sjmisc)
```

# Load data 
```{r load.data, include = FALSE}
# from "Galapagos_PAM_allsites.Rmd"
# Remove sites with odd data or different temp profiles
PAM_all <- read_csv("/Users/loga8761/github/PAM/Galapagos_all.csv") %>%
  filter(Site != "AcademyBay"& Site != "Floreana") %>%
  mutate(Site = fct_relevel(Site, 
            "Darwin", "Wolf2", "Punta_Pitt", 
            "Espanola", "Isabela"))  

pam.data <- PAM_all %>%
  filter(Species == params$Species) %>%
  filter(RampType == params$RampType) 
  
#Labels for re-ordering site names (warm -> cold)
SiteLabels <- c("Darwin", "Wolf","San Cristobal", "Espanola", "Isabela")
```

# Load data 
```{r load data, include = FALSE}
# # from "Galapagos_PAM_allsites.Rmd"
# # Remove sites with odd data or different temp profiles
# PAM_all <- read_csv("/Users/loga8761/github/PAM/Galapagos_all.csv") %>%
#   filter(Site != "AcademyBay"& Site != "Floreana") %>%
#   mutate(Site = fct_relevel(Site, 
#             "Darwin", "Wolf2", "Punta_Pitt", 
#             "Espanola", "Isabela"))  
# 
# # Heat Ramps
# PAM_heat_poc <- PAM_all %>%
#   filter(Species == "Pocillopora_sp") %>%
#   filter(RampType == "Heat") 
#   
# PAM_heat_pav <- PAM_all %>% 
#   filter(Species == "Pavona_clavus") %>%
#   filter(RampType == "Heat") 
# 
# # Cold Ramps
# PAM_cold_poc <- PAM_all %>%
#   filter(Species == "Pocillopora_sp") %>%
#   filter(RampType == "Cold") 
#   
# PAM_cold_pav <- PAM_all %>% 
#   filter(Species == "Pavona_clavus") %>%
#   filter(RampType == "Cold") 
#   
# #Labels for re-ordering site names (warm -> cold)
# SiteLabels <- c("Darwin", "Wolf","San Cristobal", "Espanola", "Isabela")
```

# Subset data
```{r load data subset, include = TRUE}
#pam.data <- x

pam.data$Geno <- as.factor(pam.data$Geno)
pam.data$Site <-  as.factor(pam.data$Site)
pam.data$Replicate <- as.factor(pam.data$Replicate)
pam.data$Treatment <- as.factor(pam.data$Treatment)
```

# Mixed Effects model 
```{r lme model, include = TRUE}
# random effect of replicate 
# Since the model is completely balanced the SS type I, II or III will provide the same result
pam.cbass.model <- lmer(PAMChange ~ Site * Treatment + (1|Replicate), data = pam.data)
anova(pam.cbass.model) # anova from lmerTest ANOVA SS Type III with ddf="Satterthwaite"
ranova(pam.cbass.model) # anova-like table for random effects
```

# Model fitting and assumptions diagnostic
```{r fitting, include = TRUE}
plot(PAMChange ~ interaction(Site,Treatment,Replicate), data = pam.data) # Box-plot homogeinity of variance
leveneTest(PAMChange ~ Site * Treatment * Replicate, data=pam.data) # formal statistical test for homogeinity of variance (not recommended due the small sample size)
```

# Residual vs Fitted values
```{r residuals, include = TRUE}
plot(pam.cbass.model) # Residual vs Fitted values
qqnorm(resid(pam.cbass.model)); qqline(resid(pam.cbass.model)) # qq plot to check for normal distribution of residuals
hist(resid(pam.cbass.model)) # histogram of residuals to check for normal distribution of residuals
shapiro.test(resid(pam.cbass.model)) # formal statistical test (not recommended due the small sample size)
```

# Compare sites by temperature treatment
```{r compare , include = TRUE}
pam.cbass.emms.reef <- emmeans(pam.cbass.model, pairwise ~ Site | Treatment, weights = "proportional", adjust="none")
summary(pam.cbass.emms.reef$emmeans)
```

# P.value adjustment with Bonferroni
```{r, bonferroni, include = TRUE}
rbind(pam.cbass.emms.reef$contrasts, adjust="bonferroni")
```

# Plot data
```{r plot}
ggplot(data=pam.data, 
    aes(x=Treatment, y=PAMChange, label= Treatment, fill=Site)) +
  #scale_fill_manual(values = c ("#56B4E9", "#E69F00"), name = "Reef site") +
  stat_boxplot(geom ='errorbar', width = 0.7, lwd=0.7)+
  geom_boxplot(width=0.7, lwd=0.7, fatten=1) +
  expand_limits(y = 0)+
  facet_grid(~Site, space = "free", scales = "free")+ #this can also be used but rows and columns have to be specified -> facet_grid(. ~ experiment)
  theme_bw() +
  annotate("segment", x=-Inf, xend=-Inf, y=-Inf, yend=Inf, colour = "black", size=2)  + 
  ylab("Delta photochemical efficiency (Fv/Fm)") +
  ggtitle(paste0(params$Species, '_', params$RampType))

title = paste0(params$Species, '_', params$RampType)
# ggsave("Figures/PAMdata_Heat_PAV_09062021.pdf", width = 10, height = 6)
```

